name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    coverage:
        name: "Coverage"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Set up Pixi"
              uses: prefix-dev/setup-pixi@v0.8.1
              with:
                  pixi-version: v0.20.1

            - name: "Install dependencies"
              run: |
                  python -m pip install coveralls

            - name: "Check code coverage"
              run: |
                  pixi run coverage

            - name: "Coveralls"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  coveralls --service=github

    lint:
        name: "Code style"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Set up Pixi"
              uses: prefix-dev/setup-pixi@v0.8.1
              with:
                  pixi-version: v0.20.1

            - name: "Run linting"
              run: |
                  pixi run lint

    test:
        name: "Test ${{ matrix.os }} with Python ${{ matrix.python-version }}"
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ["3.9", "3.10", "3.11", "3.12"]

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Set up Pixi"
              uses: prefix-dev/setup-pixi@v0.8.1
              with:
                  pixi-version: v0.20.1

            - name: "Run tests"
              run: |
                  pixi run test

    ci_success:
        name: "CI success"
        runs-on: ubuntu-latest
        needs: [coverage, lint, test]
        steps:
            - run: echo "CI workflow completed successfully"
